import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "World" });
  const { mutate: calculateDuration } = api.calculate.calculate.useMutation();

  useEffect(() => {
    calculateDuration({
      playlistId: "PL0oeth88zfALezDAUbqrBYPsEb_rvWMDq",
      playbackSpeed: 2,
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center"></main>
    </>
  );
};

export default Home;
