import { type NextPage } from "next";
import Head from "next/head";
import { useMemo, useState } from "react";
import type { FormEvent } from "react";
import { api } from "../utils/api";
import PlaybackInfo from "../components/PlaybackInfo";
import CalculateForm from "components/CalculateForm";

const Home: NextPage = () => {
  const {
    mutate: calculateDurationMutation,
    data,
    isLoading,
    isSuccess,
  } = api.calculate.calculate.useMutation();

  const [playlistLink, setPlaylistLink] = useState("");

  const playlistId = useMemo(() => {
    const id = playlistLink.split("?");
    const urlParams = new URLSearchParams(id[1]);
    const list = urlParams.get("list");

    return list || playlistLink;
  }, [playlistLink]);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    calculateDurationMutation({ playlistId });
  };

  return (
    <>
      <Head>
        <title>YouTube Playlist Length</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <div>
          <CalculateForm
            playlistLink={playlistLink}
            setPlaylistLink={setPlaylistLink}
            onSubmit={handleSubmit}
          />

          <div>
            {isLoading && <div>Loading...</div>}
            {isSuccess && (
              <div className="flex flex-col">
                {[0.5, 0.75, 1, 1.25, 1.5, 2].map((speed) => (
                  <PlaybackInfo
                    key={speed}
                    duration={data.data.duration}
                    speed={speed}
                  />
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
